### PR TITLE
Yiran li/feature/table prototype

### PR DESCRIPTION
**Pull request by yiranlir**
## Describe your changes
Create new tables ‘shift_request’ and ‘shift_request_volunteer’ to exclude vehicle data for scheduler
1. shift_request: This table stores information about shift requests without any vehicle-related data. It includes details such as the shift's start time, end time, title, and status.
2. shift_request_volunteer: This table captures the association between volunteers and their shift requests. It tracks which volunteer is assigned to which shift. It includes details such as the volunteer id, request id and status(pending, confirmed, rejected).
## Issue ticket number and link
https://fireapp-emergiq-2024.atlassian.net/browse/FIR-63?atlOrigin=eyJpIjoiMGM0OGRhYjgwOWM1NGE0MGJhNmUwNDFlOTI2MTNhM2YiLCJwIjoiaiJ9

### CODE REVIEW

**Review by emilymclean — CHANGES_REQUESTED** [review]
Is there a reason you're not just modifying the existing `asset_request` tables to remove any vehicle requirements? Unless I'm missing something, they already represent this functionality

**Comment by yiranlir** [comment]
> 你为什么不直接修改现有`asset_request`表格以删除任何车辆要求？除非我遗漏了什么，否则它们已经代表了这一功能

**Comment by yiranlir** [comment]
> Is there a reason you're not just modifying the existing `asset_request` tables to remove any vehicle requirements? Unless I'm missing something, they already represent this functionality

Because now the vehicle requirements are stored in the 'asset_request_vehicle' table and also the start time and end time of this shift is stored in 'asset_request_vehicle', only the shift request title and the status is stored in the 'asset_request'. Also, the 'asset_request_volunteer' table use 'vehicle_id' as a foreign key to reference records in the 'asset_request_vehicle' table, instead of linking through 'request_id' with the 'asset_request' table.

**Review by emilymclean — CHANGES_REQUESTED** [review]
Is the plan to create an entirely new endpoint and corresponding frontend implementation? Because this feature is already fully implemented and I don't see the justification for discarding that work. I think it would be better to keep the existing feature and modify it such that a shift has a start and end date and a volunteer references a shift instead of a vehicle? Then the frontend would just need the vehicle selection removed and an updated model.

**Review by emilymclean — APPROVED** [review]
Looks good to me, thanks for bearing with me

**Comment by yiranlir** [comment]
> Looks good to me, thanks for bearing with me

Sorry for not explaining it to you earlier.

**Pull request merged**
